### ISSUE TITLE
Pin indicator on U3

### ISSUE THREAD

**Issue by marcus7070** [Manawyrm/CMM2-JLC#2]
Firstly, thanks for this project. We've just used it to make our own version. I don't have a clue how to lay out that SDRAM, I'm really appreciative that we could use your work.

On your silkscreen you have a dot that really looks like a pin 1 indicator on U3. I didn't notice it when sending off our files and it looks like JLCPCB did, decided the silk screen was correct, and flipped our U3.

![screenshot2020-12-29-163310](https://user-images.githubusercontent.com/50230945/103262051-ad66ad00-49f3-11eb-962d-7292ae252646.png)

**Comment by Manawyrm** [comment]
Ooops! Sorry!
I have released Rev.E with fixed silkscreen and released new gerber files.

Thanks for the info! 
https://tbspace.de/content/downloads/ibom_cmm2_reve.html
